version: '3.6'
services:
  nginx: 
    depends_on:
      - jenkins-master
    build: ./nginx
    restart: always
    ports:
      - 80:80
    networks:
      - nginx-net

  jenkins-master:
    build: ./jenkins-master
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nginx-net
  
  mongodb:
    build: ./mongodb
    restart: always
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles
volumes:
  jenkins-data:
  mongodb-data:
networks:
  nginx-net:
