version: '3.6'
services:
  nginx: 
    depends_on:
      - jenkins-master
      - boltbot
    build: ./nginx
    restart: always
    ports:
      - 443:443
    networks:
      - nginx-net

  jenkins-master:
    build: ./jenkins-master
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nginx-net

  mongodb:
    build: ./mongodb
    restart: always
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongo-net
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null

  boltbot:
    image: techtony96/boltbot
    depends_on:
      - mongodb
    restart: always
    networks:
      - nginx-net
      - mongo-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      
  boltbot-dev:
    image: techtony96/boltbot:dev-latest
    depends_on:
      - mongodb
    restart: always
    networks:
      - nginx-net
      - mongo-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./watchtower/docker-login.env
    command: --interval 60 --cleanup --label-enable

volumes:
  jenkins-data:
  mongodb-data:
networks:
  nginx-net:
  mongo-net:
