version: '3.6'
services:
  nginx: 
    depends_on:
      - jenkins-master
      - kibana
    build: ./nginx
    restart: always
    ports:
      - 80:80
    networks:
      - nginx-net

  jenkins-master:
    build: ./jenkins-master
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nginx-net
  
  mongodb:
    build: ./mongodb
    restart: always
    volumes:
      - mongodb-data:/data/db
    networks:
      - database-net
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --smallfiles
  
  elasticsearch:
    build: ./elasticsearch
    restart: always
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic-net
    environment:
      - es.enforce.bootstrap.checks=true
      - ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
        
  logstash:
    build: ./logstash
    restart: always
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elastic-net
    depends_on:
      - elasticsearch

  kibana:
    build: ./kibana
    ports:
      - "5601:5601"
    networks:
      - elastic-net
      - nginx-net
    depends_on:
      - elasticsearch

volumes:
  jenkins-data:
  mongodb-data:
  elasticsearch-data:
    driver: local
networks:
  nginx-net:
  elastic-net:
