version: '3.6'
services:
  nginx: 
    depends_on:
      - jenkins-master
      - kibana
      - boltbot
    build: ./nginx
    restart: always
    ports:
      - 443:443
    networks:
      - nginx-net

  jenkins-master:
    build: ./jenkins-master
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nginx-net
  
  mongodb:
    build: ./mongodb
    restart: always
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongo-net
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: --smallfiles
  
  elasticsearch:
    build: ./elasticsearch
    restart: always
    volumes:
      - elasticsearch-data:/var/lib/elasticsearch/data
    networks:
      - elastic-net
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
        
  logstash:
    build: ./logstash
    restart: always
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elastic-net
    depends_on:
      - elasticsearch

  kibana:
    build: ./kibana
    restart: always
    networks:
      - elastic-net
      - nginx-net
    depends_on:
      - elasticsearch
      
  boltbot:
    image: techtony96/boltbot
    depends_on:
      - mongodb
      - logstash
    restart: always
    networks:
      - nginx-net
      - elastic-net
      - mongo-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./watchtower/docker-login.env
    command: --interval 60 --cleanup --label-enable

volumes:
  jenkins-data:
  mongodb-data:
  elasticsearch-data:
    driver: local
networks:
  nginx-net:
  elastic-net:
  mongo-net:
