version: '3.6'
services:
  nginx: 
    depends_on:
      - jenkins-master
    build: ./nginx
    restart: always
    ports:
      - 80:80
    networks:
      - jenkins-net

  jenkins-master:
    build: ./jenkins-master
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net
volumes:
  jenkins-data:
networks:
  jenkins-net: