version: '3.6'
services:
  nginx: 
    build: ./nginx
    restart: always
    ports:
      - 80:80
    networks:
      - jenkins_net

  jenkins:
    depends_on:
      - nginx
    build: ./jenkins-master
    restart: always
    ports:
      - 8080:8080
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins_net
volumes:
  jenkins_data:
networks:
  jenkins_net: