# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:6.3.1

COPY kibana.yml /usr/share/kibana/config/

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>